name: Check One Model and Notify

on:
  schedule:
    - cron: 0 13-22 * * 1-5  # Runs M-F 9am-6pm (actions is in UTC)
    # - cron: 0 13 * * 1-5  # Set to Runs M-F 9am (actions is in UTC) until fix
  workflow_dispatch:     # Allow manual runs

permissions:
  contents: write  # 👈 this is what gives it permission to push

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECEIVER_ADDRESS: ${{ secrets.RECEIVER_ADDRESS }}
        run: python one_model_update.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Update data" || echo "No changes"
          git push
